apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-devops-proj
    namespace: my-proj
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-devops-proj
    template:
        metadata:
            labels:
                app: my-devops-proj
        spec:
            containers:
                - name: my-devops-proj
                  image: vishnu2117/devops-proj-1:latest
                  ports:
                      - containerPort: 3000
