apiVersion: v1
kind: Service
metadata:
    name: devops-service
    namespace: my-proj
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 3000
    selector:
        app: my-devops-proj

